name: midtreats

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: python manage.py runserver ${DJ_ADDRPORT}
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    entrypoint: ./docker/api/entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

volumes:
  pg_data:
